version: 0.2
phases:
  pre_build:
    commands:
      - echo This will run npm install to install the dependencies...
      - npm install
  build:
    commands:
      - echo Actually run the build process
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
